#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 

bspc config border_width         2
bspc config window_gap           5
#bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config -m focused top_padding

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=floating
bspc rule -a qvidcap state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Xfce4-terminal state=floating
bspc rule -a flameshot state=floating
bspc rule -a Gnome-pomodoro state=floating 
bspc rule -a Xfce4-notes state=floating
bspc rule -a Eom state=floating

wmname LG3D &
flameshot &
nm-applet &
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &
feh --no-fehbg --bg-fill -Z ~/Pictures/Wallpaper/wallpaper2.png &
#feh --no-fehbg --bg-fill -Z ~/Pictures/Wallpaper/bg_8.jpg &
#feh --no-fehbg --bg-fill -Z ~/Pictures/Wallpaper/wallpaper_kata.png &
picom -o 0.75 -D 2 -m 0.88 -i 1.0 -e 1.0 --active-opacity 1.0 --no-fading-openclose &
$HOME/.config/polybar/launch3.sh &
xinput set-prop 12 283 1 &
dunst -config ~/.config/dunst/dunstrc &
